[package]
name = "dijkstra"
version = "0.1.0"
authors = ["Jarry Xiao <jarry.xiao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
